name: Reusable Workflow user

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  docker:
    uses: kaali09/test-github-action/.github/workflows/reusable.yaml@debug
    with:
      image_name: my-awesome-app
      tag: $GITHUB_RUN_NUMBER
        #secrets:
        #  registry_username: ${{secrets.REGISTRY_USERNAME}}
        #  registry_password: ${{secrets.REGISTRY_PASSWORD}}
